### ISSUE TITLE
This is a dup of the official library

### ISSUE THREAD

**Issue by Rich2k** [ztec/adLDAP#5]
Please fork and pull request to https://github.com/Rich2k/adLDAP not releasing a separate library

**Comment by stevebauman** [comment]
Yea this library either needs to be removed, or united with official library (with the official library taking precedence). This package is severely out of date and contains some extremely limiting bugs that were fixed years ago!

For example on line [Line 328] ( https://github.com/ztec/adLDAP/blob/master/lib/adLDAP/adLDAP.php#L328) in adLdap/adLdap.php.

**Comment by stevebauman** [comment]
Released updated fork on packagist:

`"stevebauman/adldap-fork": "4.0.*"`

[Packagist link] (https://packagist.org/packages/stevebauman/adldap-fork)

This fork will be consistently updated to the main repo.

**Comment by halfer** [comment]
FYI, this issue [has been raised in a Stack Overflow question](http://stackoverflow.com/q/29396915).

**Comment by Wirone** [comment]
Guys, will it be solved? I read this discussion but I still see that `adldap/adldap` on Packagist points to this "fork", not to @Rich2k's repo, so there is only `v4.0.2` version available. Like @halfer said, there is Stackoverflow thread on this issue and it would be great to clean up this mess...

And there is v5 in different organization/repo..

**Comment by stevebauman** [comment]
@Wirone, this won't be cleaned up. Both @ztec and @Rich2k have been inactive for close to a year, and @Rich2k has also left the Adldap organization he's created.

I'd suggest using Aldap2 https://github.com/adldap2/adldap2, or @ChadSikorra's LDAP Tools https://github.com/ldaptools/ldaptools

**Comment by Wirone** [comment]
@stevebauman but `v4.0.4` does not have `composer.json` and can't be installed and `v4.0.5` has namespaces and requires additional changes in our project. I just wanted to clean up our project and move some libraries to Composer's vendors. Lack of `composer.json` for `v4.0.4` relates to all repos (https://github.com/adldap/adldap, https://github.com/Rich2k/adLDAP). How to install exactly v4.0.4?

**Comment by Rich2k** [comment]
adldap2 has been sync'd into adldap main repo and @stevebauman I've invited you to the team. composer.json is now active in master and packageist should be pointing adldap/adldap to https://github.com/adldap/adLDAP.git

**Comment by Wirone** [comment]
@Rich2k @stevebauman I ended up with own [fixed fork](https://github.com/CoditoNet/adLDAP/tree/v4.0.4) which installs correctly via Composer.

Note: tags can be removed from Github so the best solution would be to add `composer.json` to the code to `adldap/adldap@v4.0.4` and update tag in main repo, so that version could be used without side repos.

**Comment by ztec** [comment]
This fork should not be used anymore.
I should ad a big "DEPRECATED" warning in the README.

I created this fork when needed, now it's not needed as the official maintainer handle it in github. If this is not the case anymore, maybe we can decide for a new fork, or have multiple maintainer in the adldap organisation ?  (If the author allow it)

**Comment by stevebauman** [comment]
@Rich2k Well if it isn't the man himself! Thanks for the invite, as well as the Adldap2 merge!

Also, unless you've changed your visibility in the organization, you can see from the google web cache that there was indeed no one listed inside the Adldap organization:

http://webcache.googleusercontent.com/search?q=cache:z6V_RrlPYb8J:https://github.com/orgs/adldap/people+&cd=1&hl=en&ct=clnk&gl=ca

Even still, if people visibly see no one in an organization, they're going to assume a dead package.

**Comment by ztec** [comment]
Does this PR help ? #10

**Comment by Wirone** [comment]
@ztec, I could swear I saw `adldap/adldap` on Packagist was pointing here (as I wrote 1 hour ago) and now I see it's properly pointing to [main repo](https://github.com/adldap/adLDAP)... How's that possible?

**Comment by stevebauman** [comment]
@Wirone you're not wrong, it was pointing to this repo, it was changed a moment ago to the proper repository.

**Comment by Wirone** [comment]
@stevebauman Good, I thought I was crazy ;-)

Anyway, `v4.0.4` in `adldap/adldap` still does not have `composer.json` and can't be installed properly.

**Comment by ztec** [comment]
When i created this repository, packagist created some versions.
When @Rich2k asked @Seldaek to gain ownership of the project, it pointed to the new repository (the one of @Rich2k )
BUT, all previous version were still there ! With references to this repository.

I think @Rich2k removed some stuff in Packagist, or maybe it's the new version that behave differently.

**Comment by ztec** [comment]
Even the cache google display some version few days ago :-) http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fpackagist.org%2Fpackages%2Fadldap%2Fadldap&oq=cache%3Ahttps%3A%2F%2Fpackagist.org%2Fpackages%2Fadldap%2Fadldap&aqs=chrome..69i57j69i58.985j0j4&sourceid=chrome&es_sm=122&ie=UTF-8

**Comment by stevebauman** [comment]
@ztec Yea I don't really agree with the way @Rich2k synced the Adldap2 repo. Not only did it remove the existing `v4.0.2` version from packagist, but it also removed all Adldap2 contribution history from the community (@wunc, @strebl, @samwilson) and I. The Adldap2 repo should have been merged into a separate branch, with the commit history.

**Comment by Rich2k** [comment]
@stevebauman feel free to git rebase the last merge and pull the entire history across if you have the time

**Comment by Seldaek** [comment]
Hey folks I haven't read everything and I don't have time to right now but in case you come to an agreement and need me to do something packagist-wise please mention me and explain clearly :)

**Comment by wunc** [comment]
I would suggest using the adldap/adldap repo as the main for this project, as long as there is someone (or more than one) who can actively maintain and manage PRs.

I'm not a git guru, but it seems like the something like the following needs to happen in adldap/adldap:
- Fix the repo so that v4.0.4 shows up in packagist again, perhaps via
  - git revert the last 2 commits, or
  - git reset to adldap/adLDAP@ee471d2243124dcf29efd8c079456cc56e2fa6e7, or
  - start a 4.0 branch?
- Tag another release to integrate commits since v4.0.4, perhaps tag v4.0.5 at adldap/adLDAP@ee471d2243124dcf29efd8c079456cc56e2fa6e7
- Merge in Adldap2 into a 5.0 branch, retaining commit history, as suggested by @stevebauman 
- Tag a a release on the 5.0 branch: 5.0.0-alpha.1
- Continue development on the 5.0 branch
- ....
- Profit! (or at least feeling good about getting a useful project back into active status)

**Comment by ztec** [comment]
I agree with @wunc 
We should have some version (v4.0.4 for example) in packagist. A branch/tag to a commit that contain the composer.json and the version that is goo should be enough. 
@Rich2k  If you make all version required appeared in the official repository, then i will remove this one. 

@all, what are the version we need to see in the official adldap repository ? (for my part, v4.0-stable or anythings close enough. I will update package that depend on it https://packagist.org/packages/ztec/security-active_directory)

**Comment by Wirone** [comment]
@ztec we've been using copypasted adLDAP v4.0.4 in one of crucial projects and now, when I want change it to Composer, from our point of view tag `v4.0.4` with proper `composer.json` is required.

For now, [as I said](https://github.com/ztec/adLDAP/issues/5#issuecomment-112421061), we're using fixed fork, but I think it should be done in main repo.

**Comment by webfractor** [comment]
https://github.com/adldap/adLDAP has the tag for 4.0.4, pretty sure if you just make this available via packagist then you'll have a bunch of consumers satisfied. Especially those of us that using them for enterprise apps. I know it will keep my boss of my back...

**Comment by stevebauman** [comment]
Apologies for the long response here.

@wunc I completely agree with this, and this is definitely the path that should be taken. However my only hesitation with using the actual Adldap repository right now, is that I don't have Administrator privileges. This means that if @Rich2k disappears for another while, I cannot add or manage contributors in the future, and I'm the sole developer who has to manage PR's and Issues, not to mention continue Adldap v5 development. I also don't have permission to manage Adldap through packagist, so unfortunately I'm hesitant to drop everything and run to the original repository.

**Comment by strebl** [comment]
@stevebauman I totally understand that.
I think you should get administrator privileges...
